"""Shared secret handling for the CryoStack Connector relay.

Two independent capabilities protect the relay; neither is the visible
``session_id``:

* ``control_secret`` -- per session, high entropy. Authorises the browser/gateway
  -> relay control plane (issue command, owner-scoped status). It is generated by
  the relay and returned only to the CryoStack kernel that created the session.
* ``session_secret`` -- per session, high entropy. Authorises a connector's
  WebSocket registration. Delivered to the connector only through the one-time
  pairing exchange, never in a URL.

An optional *deployment* token (:data:`DEPLOYMENT_TOKEN_ENV`) gates session
creation in the real deployment so ``owner_user_id`` on a session is trustworthy
and anonymous session-creation spam is rejected. When the env var is unset
(tests, single-user dev) creation is open but still requires a non-empty
``owner_user_id``.
"""
from __future__ import annotations

import hmac
import os
import secrets
import stat
from pathlib import Path

#: env var holding the shared deployment token (set by deployment/services.sh)
DEPLOYMENT_TOKEN_ENV = "CRYOSTACK_RELAY_CONTROL_TOKEN"

#: on-host file the deployment token is persisted to (mode 0600)
DEFAULT_TOKEN_FILE = Path.home() / ".cryostack" / "relay_control_token"

#: names that must never be written to a log line, provenance record or URL
SECRET_FIELD_NAMES = ("control_secret", "session_secret", "pairing_code", "password")


def new_secret(nbytes: int = 32) -> str:
    """A URL-safe, high-entropy capability string."""
    return secrets.token_urlsafe(nbytes)


def new_pairing_code() -> str:
    """A short, human-transferable one-time code (unambiguous alphabet)."""
    alphabet = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"
    raw = "".join(secrets.choice(alphabet) for _ in range(10))
    return f"{raw[:5]}-{raw[5:]}"


def constant_time_equal(a: str | None, b: str | None) -> bool:
    """Timing-safe string comparison that never raises on ``None``/type."""
    if not isinstance(a, str) or not isinstance(b, str) or not a or not b:
        return False
    return hmac.compare_digest(a, b)


def deployment_token() -> str | None:
    """The shared deployment token from the environment, or ``None``."""
    value = (os.environ.get(DEPLOYMENT_TOKEN_ENV) or "").strip()
    return value or None


def ensure_deployment_token(path: Path | None = None) -> str:
    """Return the persisted deployment token, creating it (mode 0600) once.

    Used by ``deployment/services.sh`` so the relay and the Voila/gateway
    process share one value:

        export CRYOSTACK_RELAY_CONTROL_TOKEN="$(python3 -m \\
            icesee_jupyter_book.core.connector_relay_auth ensure)"
    """
    env = deployment_token()
    if env:
        return env

    path = path or DEFAULT_TOKEN_FILE
    if path.is_file():
        token = path.read_text(encoding="utf-8").strip()
        if token:
            _harden(path)
            return token

    token = new_secret(32)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(token + "\n", encoding="utf-8")
    _harden(path)
    return token


def _harden(path: Path) -> None:
    try:
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)  # 0600
    except OSError:
        pass


def redact(payload):
    """Deep-copy ``payload`` with known secret fields replaced by ``"***"``.

    Use before logging or persisting anything that may carry a command payload.
    """
    if isinstance(payload, dict):
        return {
            k: ("***" if k in SECRET_FIELD_NAMES else redact(v))
            for k, v in payload.items()
        }
    if isinstance(payload, (list, tuple)):
        return type(payload)(redact(v) for v in payload)
    return payload


if __name__ == "__main__":  # pragma: no cover - deployment helper
    import sys

    if len(sys.argv) == 2 and sys.argv[1] == "ensure":
        print(ensure_deployment_token())
    else:
        print("usage: python -m icesee_jupyter_book.core.connector_relay_auth ensure",
              file=sys.stderr)
        raise SystemExit(2)
